// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MlFutebol.Data.Context;

#nullable disable

namespace MlFutebol.Data.Migrations
{
    [DbContext(typeof(MlDbContext))]
    partial class MlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MlFutebol.Bussiness.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Itens", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6fd50f6-8b0a-44cb-9c3e-b39fcf3d5526"),
                            Nome = "Chuteira",
                            Pontos = 4
                        },
                        new
                        {
                            Id = new Guid("d8e00bc4-1a1b-40f0-9080-1cca0c9ef5b5"),
                            Nome = "Caneleira",
                            Pontos = 3
                        },
                        new
                        {
                            Id = new Guid("50dd42ca-1585-4105-81a8-032bbcef0cf1"),
                            Nome = "Gatorade",
                            Pontos = 2
                        },
                        new
                        {
                            Id = new Guid("c007911c-e13d-45b3-8437-4954eca65973"),
                            Nome = "Camisa",
                            Pontos = 1
                        });
                });

            modelBuilder.Entity("MlFutebol.Bussiness.Entities.ItemInventarioJogador", b =>
                {
                    b.Property<Guid>("JogadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("JogadorId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("ItensInventarioJogador", (string)null);
                });

            modelBuilder.Entity("MlFutebol.Bussiness.Entities.Jogador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CartoesTomados")
                        .HasColumnType("int");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("PosicaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Suspenso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("TimeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PosicaoId");

                    b.HasIndex("TimeId");

                    b.ToTable("Jogadores", (string)null);
                });

            modelBuilder.Entity("MlFutebol.Bussiness.Entities.Posicao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Posicoes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("51dd9d2f-3fd2-40d1-a5d1-a550ee478139"),
                            Nome = "Lateral Direita"
                        },
                        new
                        {
                            Id = new Guid("7a558ec4-2b9a-4cb8-8284-79ef569e498c"),
                            Nome = "Centro Avante"
                        },
                        new
                        {
                            Id = new Guid("84a0fe7f-7721-4a89-b39f-d19ae7cedfd4"),
                            Nome = "Goleiro"
                        },
                        new
                        {
                            Id = new Guid("1a85f056-9886-4400-9225-4061868dc77f"),
                            Nome = "Lateral Esquerda"
                        },
                        new
                        {
                            Id = new Guid("559a4868-0998-4aef-9bdc-a0bb03c18092"),
                            Nome = "Meia"
                        },
                        new
                        {
                            Id = new Guid("8dbb9861-0d50-496b-92a4-72cf652b3c3d"),
                            Nome = "Zagueiro"
                        },
                        new
                        {
                            Id = new Guid("cacf7b1c-ec85-464b-9f89-65e7d30d9135"),
                            Nome = "Atacante"
                        },
                        new
                        {
                            Id = new Guid("17697393-9f7e-490d-b6d7-f252617d59de"),
                            Nome = "Meia - Atacante"
                        },
                        new
                        {
                            Id = new Guid("a774626b-a57b-4e07-9c86-a89bb47e6f68"),
                            Nome = "Volante"
                        });
                });

            modelBuilder.Entity("MlFutebol.Bussiness.Entities.Time", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Serie")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Times", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("67c1c3cd-cbc3-4972-8e25-4e113cd03b17"),
                            Nome = "Corinthians",
                            Serie = "A"
                        },
                        new
                        {
                            Id = new Guid("b97cb710-cceb-456d-8286-2782b53043a3"),
                            Nome = "São Paulo",
                            Serie = "A"
                        },
                        new
                        {
                            Id = new Guid("9cff0534-973d-4e0b-885f-7179bb2eaebd"),
                            Nome = "Palmeiras",
                            Serie = "A"
                        },
                        new
                        {
                            Id = new Guid("f06ea5e4-7cc1-4dcd-abbf-d6a9750fdbd8"),
                            Nome = "Santos",
                            Serie = "B"
                        },
                        new
                        {
                            Id = new Guid("f528a929-3f46-45ee-9eda-c2e88961cbc1"),
                            Nome = "Ituano",
                            Serie = "B"
                        },
                        new
                        {
                            Id = new Guid("4c005e2a-72d9-4dab-b849-75b3fc9ee61c"),
                            Nome = "Gremio Prudente",
                            Serie = "B"
                        },
                        new
                        {
                            Id = new Guid("909168c3-6467-45c0-9929-66a8b7036891"),
                            Nome = "Varzea",
                            Serie = "C"
                        },
                        new
                        {
                            Id = new Guid("73d44936-6042-4c84-9ef3-fe80b7844b3c"),
                            Nome = "Canarinho",
                            Serie = "C"
                        },
                        new
                        {
                            Id = new Guid("98843bd0-7fca-46cc-9c17-53cbe2951ba1"),
                            Nome = "Vasco",
                            Serie = "C"
                        });
                });

            modelBuilder.Entity("MlFutebol.Bussiness.Entities.ItemInventarioJogador", b =>
                {
                    b.HasOne("MlFutebol.Bussiness.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .IsRequired();

                    b.HasOne("MlFutebol.Bussiness.Entities.Jogador", "Jogador")
                        .WithMany("Inventario")
                        .HasForeignKey("JogadorId")
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("MlFutebol.Bussiness.Entities.Jogador", b =>
                {
                    b.HasOne("MlFutebol.Bussiness.Entities.Posicao", "Posicao")
                        .WithMany("Jogadores")
                        .HasForeignKey("PosicaoId")
                        .IsRequired();

                    b.HasOne("MlFutebol.Bussiness.Entities.Time", "Time")
                        .WithMany("Jogadores")
                        .HasForeignKey("TimeId")
                        .IsRequired();

                    b.Navigation("Posicao");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("MlFutebol.Bussiness.Entities.Jogador", b =>
                {
                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("MlFutebol.Bussiness.Entities.Posicao", b =>
                {
                    b.Navigation("Jogadores");
                });

            modelBuilder.Entity("MlFutebol.Bussiness.Entities.Time", b =>
                {
                    b.Navigation("Jogadores");
                });
#pragma warning restore 612, 618
        }
    }
}
